### ISSUE TITLE
Mod doesn't show OnBakeMesh SyncMethod for ProceduralMesh components

### ISSUE THREAD

**Issue by Nytra** [art0007i/ShowDelegates#7]
I think it should show this because it's a ButtonEventHandler, it just has a SyncMethod type of Delegate which is being filtered out in the code for some reason.

**Comment by art0007i** [comment]
if you are referring to this line: https://github.com/art0007i/ShowDelegates/blob/master/ShowDelegates/ShowDelegates.cs#L151
then it's vanilla behavior, as you would expect with show only vanilla config option

**Comment by Nytra** [comment]
Oh my bad. However I'm pretty sure this sync method doesn't show up anyway regardless of that option.

**Comment by art0007i** [comment]
In which case I am guessing that it's because it's a subtype syncmethod rather than the type itself, for example BoxMesh class does not have a OnBakeMesh function itself, but it inherits it from ProceduralMesh. at least I think that's what's happening here.

**Comment by Nytra** [comment]
Is it intended to not show sync methods from sub types?

**Comment by art0007i** [comment]
I think it should show it. But it's really just using whatever data froox collects about the syncmethod attributes so I guess I have to add extra workaround for this.

**Comment by art0007i** [comment]
found the cause. apparently C# [GetMethods](https://learn.microsoft.com/en-us/dotnet/api/system.type.getmethods?view=netframework-4.7.2) function shows methods of subtypes but only if they are public
[sharplab example](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgAwFgBQiCM65IARyYB0ASgKYBmANmQMbACWA9lANw76FEAyDUAjuwwI8FJkzwg8AZwgAjYAE8ADmTwBvdAF90AQznTgYXfQIjZClWs1oAkHADMBACx5gZQ5gAUAShu2dO2UwBgA3XXcXNw9gBF9/QMDHMzwAW10+DXQ8HLMEdVzCvHRbWxL7TABOL0IkIgApJj4vACIAGjx2tysmCi8xJh8iAHEyYABZMYALJgATaS8AIT5ZvgBzADEqXTXpIgBJKENdKFo1GDxlqFWoTe3dogAFeSoGWjwLq5u7nb2AORYzzkr1oQwAymQaPQvF4AB4+AC8AD5YUQACpMMFGda+Hx4oSlQjVWoNJpQVodLpKVS9LwWalkIajCbTOYLL7rLa/A5HYAnM4fS4rTn3PZAkGCjm3LkPAFQcVvcGQujAGHw5GojFYkK3XH49DZXKJIA==)

not sure what I should do with this, I guess I'd have to recursively scan types for syncmethods manually because c# reflection can't do it on it's own

**Comment by art0007i** [comment]
try this one: https://github.com/art0007i/ShowDelegates/releases/tag/2.2.5-pre1
you can also read the commit cause it's kinda nasty and maybe you have a better idea on how to fix this

**Comment by art0007i** [comment]
oh I can try it. I had no idea it even exists
